version: '3.1'
services:
  #Nginx Service
   webserver:
     image: nginx:alpine
     container_name: webserver
     restart: unless-stopped
     ports:
       - "80:80"
       - "443:443"


#Mysql DB
   db:
     image: mysql:5.7
     container_name: Mysqldb
     restart: unless-stopped
     volumes:
       - db_data:/var/lib/mysql
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: mydb
       MYSQL_USER: new-user
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_root_password
       - db_password
secrets:
   db_password:
     file: db_password.txt #should be created bfr running docker-compose file
   db_root_password:
     file: db_root_password.txt #should be created bfr running docker-compose file

volumes:
    db_data:
    
   #jenkins download using Docker compose 
   jenkins:
     image: jenkins/jenkins:lts
     privileged: true
     user: root
     ports:
       - 8080:8080
       - 50000:50000
     container_name: jenkins-lts
     volumes:
       - ~/jenkins_home:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock
       - /usr/local/bin/docker:/usr/local/bin/docker


  

